# Generated by Django 5.0.7 on 2025-02-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuariopersonalizado_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'verbose_name': 'usuario'},
        ),
    ]
