# Generated by Django 5.0.7 on 2025-01-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_usuario_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
    ]
